### ISSUE TITLE
What’s the license?

### ISSUE THREAD

**Issue by GorEldeen** [xSnapi/Heavy#2]
Hey there, I’ve found your project quite impressive and cool, I want to make a light weight 2D game engine and your engine is really gonna help much to not start from zero, But I didn’t find any license, Can i modify it for my own?

**Comment by xSnapi** [comment]
yes

**Comment by xSnapi** [comment]
although i don't recommend it, but go ahead

**Comment by GorEldeen** [comment]
Thank you so much man

> although i don't recommend it, but go ahead

At first i will try to learn from your code and make my own, If I couldn’t I would use some of your code directly, Thanks again!
